### PR TITLE
Changed from deprecated .scala build definition to .sbt + 2.12 cross-compilation

### PR DESCRIPTION
**Pull request by jpsacha**
Also added cross-compilation for Scala 2.12.0. Everything works fine, but the things requiring subcut. It did not release 2.12 binaries yet.

### CODE REVIEW

**Comment by vigoo** [comment]
Wow, thanks! Will merge when subcut is released (or we can also remove that dependency temporarily)

**Comment by jpsacha** [comment]
If possible. I would remove subcut dependencies, there was no much activity
in the project. I would not hold rest of the scalafxml for the subcut.
On the other hand. It is possible to build subcut with Scala 2.12 (you only
need to update subcut scalatest dependency). So an option would be to
locally build subcut with 2.12 so scalafxml can be build without
modifications.

**Comment by mfelsche** [comment]
:+1:

**Comment by mfelsche** [comment]
:+1: :+1: :+1:

**Comment by ayoub-benali** [comment]
When are the binaries for scala 2.12 going to be published ?

**Comment by vigoo** [comment]
Now, sorry for the delay :)

**Pull request merged**
